{{- if and .Values.rbac.create .Values.rbac.clusterWide }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeforge-agent
subjects:
  - kind: ServiceAccount
    name: kubeforge-agent
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kubeforge-agent
  apiGroup: rbac.authorization.k8s.io
{{- end }}
