{{- if and .Values.rbac.create (not .Values.rbac.clusterWide) }}
{{- range .Values.rbac.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubeforge-agent
  namespace: {{ . }}
subjects:
  - kind: ServiceAccount
    name: kubeforge-agent
    namespace: {{ $.Release.Namespace }}
roleRef:
  kind: Role
  name: kubeforge-agent
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
